### ISSUE TITLE
Remove import-valid in favor of no-filter-irr, no-filter-rpki, no-filter-bogon

### ISSUE THREAD

**Issue by natesales** [natesales/wireframe#17]
Instead of the useful but confusing peer type of `import-valid`, there should be boolean values to disable certain filters.

**Comment by hamptonmoore** [comment]
To get this right the user would simply use the "peer" type then set no-filter-irr: true?

**Comment by natesales** [comment]
Yes, that's the idea. To make bcg configs even simpler to understand, maybe the `type` field could be removed altogether and replaced by boolean fields for each option. This would need some careful thought in how things like communities and export control is set up...

For now, this issue should just be for filter control with no-filter-irr, no-filter-rpki, and no-filter-bogon.

**Comment by hamptonmoore** [comment]
Current no-filter disabled bogons, should no-filter be changed to an accept all?

**Comment by natesales** [comment]
Added in v4.0.0
