### ISSUE TITLE
Implement more action communities

### ISSUE THREAD

**Issue by Gabitzuu** [natesales/wireframe#31]
It would be useful to have communities like:
- Prepend X times to ASx
- Do not announce to X
- Announce only to X (maybe?, not so sure about that tho)

One more thing, it would be nice to have the option to override the templates.

**Comment by natesales** [comment]
v4.0.0 changes the way communities work, so this can all be implemented as [augments](https://natesales.github.io/wireframe/configuration/#augments). Complete template overrides are out of scope imo, but if there are any features that you need that can't be accomplished with augments, let me know and I'd be glad to add them natively.
